### ISSUE TITLE
[Feature Request] allow embed image link in the composer

### ISSUE THREAD

**Issue by luofan189** [NodeBB/nodebb-plugin-composer-default#10]
Currently, we could only upload images from local. It would be great if we could allow adding image links to the composer and auto-render it in the preview.

**Comment by pitaj** [comment]
This is dependent on the post parser, but I'll assume you're using Markdown, since it is the default.

In markdown, ember images like so:

```markdown
![image alt name](https://image.link/path)
```

If your question is really about adding the option for the image button to add images by url, then yeah, that seems like a good idea.

**Comment by luofan189** [comment]
Yeah, I mean add images by url. It will be great if the default composer has this.

**Comment by bdharrington7** [comment]
@luofan189 check out my imgbed plugin if you're still looking for a solution for this 

https://community.nodebb.org/topic/475/nodebb-plugin-imgbed-image-embedding-with-only-a-url
