### ISSUE TITLE
How to remove picture button in composer?

### ISSUE THREAD

**Issue by kidswong999** [NodeBB/nodebb-plugin-composer-default#104]
Hi, I want to remove picture button. 
![image](https://user-images.githubusercontent.com/9582040/37698487-27bff1e2-2d1e-11e8-92ec-859e5902eda7.png)

Because users always paste a local picture path in web url.

like this:`![](C://aa.jpg)`

**Comment by kidswong999** [comment]
https://github.com/NodeBB/nodebb-plugin-composer-default/blob/master/static/lib/composer/formatting.js#L54

In the formatting.addComposerButtons method, I don't know where this variable is. maybe from nodebb instead of plugin-composer?

**Comment by kidswong999** [comment]
I just change the composer template.
I know this method is stupid......

https://github.com/kidswong999/nodebb-plugin-composer-stupid

**Comment by JeremyLyu** [comment]
> I just change the composer template.
> I know this method is stupid......
> 
> https://github.com/kidswong999/nodebb-plugin-composer-stupid

execute the JS in the ACP.
 祝你好运

```
$(window).on('action:composer.enhanced', function (evt, data) {
          $(".formatting-group li[title='Picture']").css("display","none");
          $(".formatting-group li[title='Link']").css("display", "none");
          $(".formatting-group li[title='Zen Mode']").css("display", "none");
          $(".formatting-group li[title='Upload Image'] i").removeClass('fa-cloud-upload');
          $(".formatting-group li[title='Upload Image'] i").addClass('fa-picture-o');
});
```
<img width="1550" alt="WeChat4bf0b664c2a9954925382e60385c1f2c" src="https://user-images.githubusercontent.com/8035331/56798358-2853e980-6849-11e9-8316-cc3380de5b8d.png">
