### ISSUE TITLE
Saved drafts open on every page

### ISSUE THREAD

**Issue by uplift** [NodeBB/nodebb-plugin-composer-default#105]
When draft composer content is saved in local storage, navigating between different sections of the forum keeps opening the composer with the saved content. 

Shouldn't it only open when you navigate back to the topic the content was saved against? Maybe I miss understand the functionality.

Would it be possible to add someway to disable the draft behaviour?

**Comment by barisusakli** [comment]
Seems like a bug to me

**Comment by julianlam** [comment]
Depends... it should open on a new window/tab, but not during regular navigation.
