### ISSUE TITLE
Text area readonly attribute seems to be set but never unset

### ISSUE THREAD

**Issue by russellhill** [NodeBB/nodebb-plugin-composer-default#112]
The text area used in the composer window has the `readonly` attribute set at the point the composed item is submitted. There doesn't seem to be a corresponding unset of that attribute though.

See: https://github.com/NodeBB/nodebb-plugin-composer-default/blob/c0d914ce3f838f98c3925da3320e042f081bbc70/static/lib/composer.js#L635

This means that if there is another plugin that is say, checking the content of the composed item for profanities on `filter:topic.post` or `filter:topic.create` (for example) and indicates an error to the user, when the user re-opens the composer to correct their post, the text area is still `readonly` so they are unable to correct that part of their post.

Is there any way of working around this?

**Comment by julianlam** [comment]
Thanks for reporting, sounds like a bug to me 🙂

**Comment by russellhill** [comment]
Locally if I change this:

```
	function onShow() {
		$('html').addClass('composing');
	}
```

To this:

```
	function onShow() {
		$('html').addClass('composing');
		$('.composer-container textarea.write').prop('readonly', false);
	}
```

It "solves" the issue. I suspect there may be a cleaner way.

**Comment by julianlam** [comment]
v6.1.6
