### ISSUE TITLE
Quote 'said in' not localized by user settings

### ISSUE THREAD

**Issue by Jey-Cee** [NodeBB/nodebb-plugin-composer-default#119]
On our forum (nodeBB 1.11.2) we have set the system language to English, because its multilingual. 
But if the user sets the language for itself to an other language the qoute uses system language.

Could you please fix this?

**Comment by pitaj** [comment]
It uses the system default language because that text is included in the post itself.

Every user sees that text, so translating it in the poster's language would mean most of your users may not be able to read it.
