### ISSUE TITLE
Can The Order Of Icons In Composer's Toolbar Be Customized?

### ISSUE THREAD

**Issue by huzhw8** [NodeBB/nodebb-plugin-composer-default#122]
Thank for your composer, and it is really a great tool. But I have a puzzle these days.
Is there any way to customized the order of  `Toolbar`?
After install some plugins linked to composer, the icons will be chaotic sequence. 
![image](https://user-images.githubusercontent.com/34414914/55224393-66122200-524b-11e9-83e3-531f3ae5101d.png)
And I do not find any setting to adjust them.
So I come here for information.
Thanks again!

**Comment by julianlam** [comment]
Not explicitly, no... but there is the "order active plugins" screen in the plugins page that might affect this, though I am not sure. Can you give it a try?
