### ISSUE TITLE
Provide a preview mode for small screens

### ISSUE THREAD

**Issue by alfazaz** [NodeBB/nodebb-plugin-composer-default#126]
Hello !

When screen is too small, preview is not possible for now.

Is it possible to have a toggle to switch between writer-container and preview-container in these situations ? For example, click on a "show preview" to show only the preview-container (hide writer-container) and click on a "hide preview" to hide it.

It would be a greater experience on mobile or small windows for example.

Thanks !

**Comment by pitaj** [comment]
Likely we would add an extra button to the navbar at the top of the window, or at the beginning of the formatting bar.

**Comment by julianlam** [comment]
PRs welcome or I can take a look later this week

**Comment by julianlam** [comment]
v6.3.1

**Comment by alfazaz** [comment]
@julianlam
Just a remark (always for small screens) : when we close the composer in previewing mode, we have the same mode on next edition, which is disturbing for users (it's strange to open the composer and not being able to type anything in it...).
The composer should always start in editing mode no ?

**Comment by julianlam** [comment]
@alfazaz Yes that makes sense, I will investigate this issue.

**Comment by julianlam** [comment]
composer-default@6.3.3

**Comment by alfazaz** [comment]
Thanks !

**Comment by alfazaz** [comment]
@julianlam 
It works for small screen correctly now. But I think there is a border effect : on large screens, the preview is hidden at start even if there is place to have the split view.

So, on small screens, it's ok now.
On large screens, the composer should always start splitted with preview (?). 
I let you decide of course...

**Comment by julianlam** [comment]
:ok_hand:

**Comment by julianlam** [comment]
v6.3.4

**Comment by alfazaz** [comment]
:-)... Thanks !
