### ISSUE TITLE
Zen mode broken...

### ISSUE THREAD

**Issue by alfazaz** [NodeBB/nodebb-plugin-composer-default#127]
On nodebb forum site (today version) and also my nodebb (v1.12.2), zen mode is broken when doing these steps (I tried it under firefox 67) :
* Go to an existant topic on nodebb forum.
* Click on answer.
* Click on "zen mode" button.
Then, this make a bad display with two upper zones but no buttons, no editor... Full screen is on but no editing is possible.

Note : there is no problem on creating a new topic...

**Comment by julianlam** [comment]
Unfortunately not seeing any issues on Firefox 67.0.4 right now, either on community.nodebb.org or my personal dev environment. Let me know if this issue persists, but I will need more reproduction steps since I am unable to repro at the moment.

**Comment by alfazaz** [comment]
@julianlam 
I still have the problem on replying to a topic... Strange... Look at the joined video to see what happens.
[bug.zip](https://github.com/NodeBB/nodebb-plugin-composer-default/files/3382705/bug.zip)
