### ISSUE TITLE
No category selector on nodebb 1.12.2 on 6.3.10 version

### ISSUE THREAD

**Issue by alfazaz** [NodeBB/nodebb-plugin-composer-default#131]
Hello !

I tried to upgrade this plugin from 6.3.9 to 6.3.10 on my nodebb 1.12.2 forum but, after that, the category selector in the composer disappears. Is it voluntary ? It's not a good thing when creating a new thread coming from /unread page for example (no possibility to choose a category).

**Comment by barisusakli** [comment]
Thanks for reporting looks to be a bug in the latest verison of the composer.

**Comment by alfazaz** [comment]
Thanks !

**Comment by alfazaz** [comment]
There's still a bug close to this one... I opened another issue for it : #132
