### ISSUE TITLE
No category selector on nodebb 1.12.2 on 6.3.11 version

### ISSUE THREAD

**Issue by alfazaz** [NodeBB/nodebb-plugin-composer-default#132]
It's not exactly a duplicate of #131 here (but seems to be close to it)... 

There is still no category selector when we want to create a new subject in a category *coming from this category*. It can be voluntary from you but, if it is the case, I still can't post a new thread : there's an error on validating the post (category doesn't exist)...

**Comment by barisusakli** [comment]
I don't know what you mean by `new subject in a category coming from this category.`

**Comment by alfazaz** [comment]
Sorry. Here are more informations :

* Go in a category page ( like https://community.nodebb.org/category/2/general-discussion )
* Click on the button "Nouveau sujet" (in french) to create a new topic
* On nodebb 1.12.2 with the 6.3.11 version of this plugin, the composer is opened but without the category selector. On saving the new post, there is an error saying that category doesn't exist.

The problem is not present on nodebb community forum but is present on my nodebb 1.12.2 + 6.3.11 plugin.

**Comment by barisusakli** [comment]
Hmm using the latest version of this plugin with an older version of nodebb isn't really supported. If you are on nodebb 1.12.2 you need to use the version of nodebb that is in `install/package.json` which is 6.2.12. Or update you NodeBB to latest master and use 6.3.11

**Comment by alfazaz** [comment]
Ok... It's strange because it's my nodebb 1.12.2 (latest stable ?) which proposes this plugin to upgrade on admin/extend/plugins#upgrade ... I thought that this page only propose upgrade for packages compatibles with the installed nodebb version.

No ?

**Comment by barisusakli** [comment]
Yeah acp lets you upgrade because package.json doesnt restrict it https://github.com/NodeBB/nodebb-plugin-composer-default/blob/master/package.json#L26 not sure if there are any breaking changes in the latest versions of composer-default but since you are getting errors there might be. What errors are you getting your javascript console when you open the composer on a category?

**Comment by alfazaz** [comment]
This error : 

> TypeError: taskbar.update is not a functioncategoryList.js:94:12
>     updateTaskbar http://localhost:5678/assets/src/modules/composer/categoryList.js?v=nh44mso3ubg:94
>     init http://localhost:5678/assets/src/modules/composer/categoryList.js?v=nh44mso3ubg:38
>     onack http://localhost:5678/assets/nodebb.min.js?v=nh44mso3ubg:10909
>     onpacket http://localhost:5678/assets/nodebb.min.js?v=nh44mso3ubg:10909
>     exports http://localhost:5678/assets/nodebb.min.js?v=nh44mso3ubg:10909
>     emit http://localhost:5678/assets/nodebb.min.js?v=nh44mso3ubg:10907
>     ondecoded http://localhost:5678/assets/nodebb.min.js?v=nh44mso3ubg:10907
>     exports http://localhost:5678/assets/nodebb.min.js?v=nh44mso3ubg:10909
>     emit http://localhost:5678/assets/nodebb.min.js?v=nh44mso3ubg:10907
>     add http://localhost:5678/assets/nodebb.min.js?v=nh44mso3ubg:10907
>     ondata http://localhost:5678/assets/nodebb.min.js?v=nh44mso3ubg:10907
>     exports http://localhost:5678/assets/nodebb.min.js?v=nh44mso3ubg:10909
>     emit http://localhost:5678/assets/nodebb.min.js?v=nh44mso3ubg:10907
>     onPacket http://localhost:5678/assets/nodebb.min.js?v=nh44mso3ubg:10907
>     setTransport http://localhost:5678/assets/nodebb.min.js?v=nh44mso3ubg:10907
>     emit http://localhost:5678/assets/nodebb.min.js?v=nh44mso3ubg:10907
>     onPacket http://localhost:5678/assets/nodebb.min.js?v=nh44mso3ubg:10908
>     onData http://localhost:5678/assets/nodebb.min.js?v=nh44mso3ubg:10908
>     onmessage http://localhost:5678/assets/nodebb.min.js?v=nh44mso3ubg:10909
>

**Comment by alfazaz** [comment]
So package.json should restrict upgrade on incompatible nodebb version if there are breaking changes.

**Comment by barisusakli** [comment]
Yeah so looks like there is a breaking change in https://github.com/NodeBB/NodeBB/commit/9b09ee0e932de46138d9d2f1c2b8749e382af36d, so we just need to update the compatibility string.

**Comment by barisusakli** [comment]
You should use `6.2.12` until nodebb 1.13.0 is released or switch to latest master.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-composer-default/commit/c4bab586ad054509408253ab2fe603cfc39880cb

**Comment by alfazaz** [comment]
Ok. Thanks !
