### ISSUE TITLE
No redirect after post a reply or new topic

### ISSUE THREAD

**Issue by andreadragotta** [NodeBB/nodebb-plugin-composer-default#136]
Hi, 

I'm working on a nodebb plugin, this plugin show a list o topics and posts and is possible to reply in the same page.
I need to remain in the same page after send reply but now che composer after the send button press start an ajaxify request. 
Is possible to disable that or stop the ajaxify.go in this case?

**Comment by pitaj** [comment]
There's a user setting that disables this behavior.

**Comment by barisusakli** [comment]
I think that setting just scrolls to your post in the same topic, he is trying to disable the redirect that happens when you post something new from the composer which doesn't seem to be possible right now.

**Comment by barisusakli** [comment]
Need a new hook to disable the redirect that is happening here https://github.com/NodeBB/nodebb-plugin-composer-default/blob/master/static/lib/composer.js#L700-L712

**Comment by julianlam** [comment]
I think a potential option here would be to attach a client-side hook to the ajaxify event and stop it prematurely if it's a new topic/reply, but I am not entirely certain if that is possible.

**Comment by andreadragotta** [comment]
I have tried to put an event listener on action:ajaxify:start and make a preventDefault(); but not work.

I've see this in the merge request https://github.com/NodeBB/nodebb-plugin-composer-default/pull/75 i think that probably fix the problem

**Comment by barisusakli** [comment]
@andreadragotta you can use 

```
$(window).on('action:composer.submit', function (ev, data) {
  data.redirect = false;
});
```
Let me know if that fixes your issue.

**Comment by andreadragotta** [comment]
@barisusakli no, not fix

**Comment by barisusakli** [comment]
Did you update to composer-default 6.3.24?

**Comment by andreadragotta** [comment]
no, current version is 6.3.21 

The plugin manager not notify any update. 
Update with npm

**Comment by andreadragotta** [comment]
With the update now work good! i don't know why the plugin manager inside nodebb not show me any updates

**Comment by barisusakli** [comment]
It takes a while for it to update in the package manager I think.
