### ISSUE TITLE
New minimumRatio

### ISSUE THREAD

**Issue by boomzillawtf** [NodeBB/nodebb-plugin-composer-default#138]
Is there some history about why this change was made?

https://github.com/NodeBB/nodebb-plugin-composer-default/commit/10147ca0e21519d9426e201ab5da9ea0faae49d6

It is hugely unpopular at our site, and I can't say that I disagree. The plan is to make our own custom patch, but I'd prefer to avoid that.

**Comment by Tsaukpaetra** [comment]
Maybe something to do with this?
8976dee55ae1786291139fa14f89976dbdfc81dc

**Comment by boomzillawtf** [comment]
Ah, so perhaps something that's better suited to a _default_ or initial setting as opposed to a _minimum._

**Comment by julianlam** [comment]
In the default composer (and quill, as well), short viewports would cause the textarea to become too small as to be unusable. The altered minimum is to counter that, although it needs some tweaking. I think setting the new minimum to .4 was a little too much, so I will revert that on Monday and re-visit this issue. Most likely a more elegant solution can be developed.

Thanks for bringing this to my attention.

**Comment by julianlam** [comment]
Closed via d2c40bb087bca45b4584c14d3c3b7384f523dd12
