### ISSUE TITLE
some item didn't work

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB/nodebb-plugin-composer-default#147]
hi
in NodeBB v1.17.0-beta.0
the below items didn't work 
![image](https://user-images.githubusercontent.com/37838903/109926805-9cc70180-7cd8-11eb-9cd5-4478f15562da.png)

**Comment by pitaj** [comment]
Can reproduce on community.nodebb.com

**Comment by julianlam** [comment]
Thank you both for reporting and verifying!

**Comment by julianlam** [comment]
This was fixed in core.
