### ISSUE TITLE
Darkened tags input - where's the css?

### ISSUE THREAD

**Issue by DieSinfo** [NodeBB/nodebb-plugin-composer-default#148]
I'm working on a dark mode of the default composer, but I have a problem with the input placeholder.
Both the title and the tags placeholder are using the variable defined in the theme variables (input-color-placeholder, #eff, Persona). 
The tags input seems to darken that color, and I also want the title input placeholder to be darkened that way, but I can't find the causative css.
Here's a picture of it.
![grafik](https://user-images.githubusercontent.com/62621213/111031846-db139d80-8409-11eb-96ac-915200108cf7.png)

Thanks in advance!

**Comment by pitaj** [comment]
I don't believe we set the color, just allow the browser to use it's default.

You can use the placeholder selector to do it yourself though https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder
