### ISSUE TITLE
Hook to reply to a specific post (customer side)

### ISSUE THREAD

**Issue by shlomo-shlomo** [NodeBB/nodebb-plugin-composer-default#156]
Is there a way to know by action hook (customer side) whether the post was sent as a general reply (1 in the picture), or as a reply to a particular post (2/3 in the picture)?
![image](https://user-images.githubusercontent.com/78599753/150331038-609d9587-8c3f-4310-8745-cce98f77152e.png)
It has meaning;
An answer to a post looks like this:
![image](https://user-images.githubusercontent.com/78599753/150331182-f62ff992-9f7e-4349-826a-ccb98741c1f0.png)
And a general answer looks like this:
![image](https://user-images.githubusercontent.com/78599753/150331437-f709ec96-e466-4ee5-a4f6-81a07c641362.png)
Not associated with a particular post.
Thank you.
@barisusakli

**Comment by shlomo-shlomo** [comment]
I tried to print the `Data` and `event` of `action:composer.submit`, but did not see anything suitable there.

**Comment by barisusakli** [comment]
When you click on the blue reply button acton:composer.submit wont have the `toPid` variable in `composerData`

**Comment by barisusakli** [comment]
These questions are better for our community forum at https://community.nodebb.org. The issue tracker is for bugs and feature requests.
