### ISSUE TITLE
Composer does not scroll

### ISSUE THREAD

**Issue by pichalite** [NodeBB/nodebb-plugin-composer-default#2]
Composer does not scroll when you type a long message. the main page starts scrolling when you reach the end.

**Comment by mrgame64** [comment]
I'm having a similar problem, except both the composer and the main page are scrolling.

**Comment by Pappmann** [comment]
same problem on mobile devices like phone or tablet (ios + android)

**Comment by bdharrington7** [comment]
This seems to be a longstanding issue. There's a PR from @pitaj that might help make it better? Mobile first guys, mobile first! :D

**Comment by pitaj** [comment]
The PR had quite a few merge issues since there have been a bunch of changes since that PR was sent in. Maybe someone could help with reducing the merge?

**Comment by bdharrington7** [comment]
I think @pichalite's recent PR's have fixed this issue 👍
