### ISSUE TITLE
duplicate image icon in toolbar

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/nodebb-plugin-composer-default#20]
![image](https://cloud.githubusercontent.com/assets/2583394/12529863/13fe61ee-c1d1-11e5-9a47-06d479a39a47.png)

One is upload, other just inserts markdowin image syntax.

We should also probably add tooltips to these buttons

**Comment by julianlam** [comment]
When is the icon `fa-picture`, and when is it `fa-upload`?

**Comment by barisusakli** [comment]
if there is a plugin with the hook filter:uploadImage it shows fa-picture, if you enable `allow users to upload regular files` then fa-upload is shown as well.

**Comment by tomamoto** [comment]
Definitely wanna give my +1 to this.  Note sure what approach would be appropriate or what plugins generally contribute to this state, but I have the same situation going on at [my board](https://board.studioyotta.com/). I'll try and pore through the code and see if this is something I could contribute on.
