### ISSUE TITLE
separate route composer bug

### ISSUE THREAD

**Issue by Shadowfaxenator** [NodeBB/nodebb-plugin-composer-default#26]
If I switch composer to a separate route, i don't see upload file icon and upload thumbnail icons

**Comment by bdharrington7** [comment]
Has anyone taken a look at this one yet?

**Comment by barisusakli** [comment]
@julianlam

**Comment by julianlam** [comment]
Thanks guys, in the middle of looking into this. Got the upload button working, but still need to get the thumb buttons to show as well.

**Comment by bdharrington7** [comment]
So for anyone still waiting for the upgrade to NBB that will have the fixes for the composer in it, I've created a patched version with julian's changes that still works with 1.0.3: 
https://github.com/bdharrington7/nodebb-plugin-composer-default/tree/v3.0.22-patch

You will have to clone this repo into your `node_modules` folder and switch to the v3.0.22-patch branch
