### ISSUE TITLE
After posting a reply, show the new post bug

### ISSUE THREAD

**Issue by exomarty** [NodeBB/nodebb-plugin-composer-default#35]
if you open the compose then change to another route and then send reply it wont send youi back to the thread

**Comment by julianlam** [comment]
I think this is actually by design, since the act of navigating elsewhere shows that a user may not want to be redirected back to the topic...

Open to discussion of course 😃

**Comment by exomarty** [comment]
Maybe but i see more the situation where you let composer opened , while doing a other thing then write the post and submit. 
If you write a post i assume you interested on the topic but who knows
