### ISSUE TITLE
Errors when using NodeBB in a subfolder with latest version

### ISSUE THREAD

**Issue by AdJones** [NodeBB/nodebb-plugin-composer-default#37]
Update: we have a PR in for NodeBB that solves this issue - it's not respecting the relative path to the forum when loading express modules.

Hi 

Since upgrading to NodeBB 1.0.3 and the latest version of this plugin, we get errors when trying to create new topics and reply to posts. _The problem only seems to occur when running NodeBB in a subfolder._

The error is:

Uncaught TypeError: Cannot read property 'newTopic' of undefined

Screenshot:

![image](https://cloud.githubusercontent.com/assets/5397442/15142735/4a04bf0a-169e-11e6-8488-1c7fa0f06cda.png)

A workaround we have found is to change the plugin's plugin.json file by removing the modules section and replacing it with the scripts section from version 3.0.11.

Thanks!

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/4621
