### ISSUE TITLE
Composer > 3.0.22 broken for NBB 1.x.x branch

### ISSUE THREAD

**Issue by bdharrington7** [NodeBB/nodebb-plugin-composer-default#40]
Hi @barisusakli I tried installing the latest composer on NBB (running the [latest from the 1.x.x branch](https://github.com/NodeBB/NodeBB/commit/a196c834d9aab4e1c27965dcca623ce12e61b4ae)) and it seems that d91843617cc3601e8db160d8ce6ce3c62e1f8697 completely broke the composer, were these changes intended for the next release of NBB? I'm getting these errors in the console right after a fresh reload of NBB:

![image](https://cloud.githubusercontent.com/assets/4553795/15562978/0dcd8ba8-22b9-11e6-975d-7a6975f3387f.png)

**Comment by julianlam** [comment]
The composer version is locked down based on the NodeBB commit. You'll need to install the version specified in package.json

**Comment by bdharrington7** [comment]
From the latest package.json in the composer:

```
nbbpm": {
    "compatibility": "^1.0.0"
  }
```

**Comment by bdharrington7** [comment]
Unless you meant the one pinned in the NBB 1.x.x branch...

**Comment by julianlam** [comment]
You need to use the version specified in NodeBB's package.json :smile:

**Comment by bdharrington7** [comment]
Oh no, that's what I was fearing...

In that case, shouldnt the nbbpm version in there composer's package.json be different? Does this only work with NBB master now?

**Comment by julianlam** [comment]
It should be, yes... so that will need fixing :)

**Comment by bdharrington7** [comment]
Ok. How long do you think it will be until the latest 1.x release of Nodebb will be compatible? Or should a 3.0.x branch be cut from 4f013870b5ac4a3985c8b0c4578fa5017adb3b0f that has bug fixes still compatible with NBB 1.0.0-1.0.3?

**Comment by julianlam** [comment]
I don't think we will be bringing compatibility of the composer back to the v1.x line (unless the change that breaks it can be done in a backwards compatible way)... that's why we lock down the composer versions -- you are not supposed to stray from it, so the proper path here would be to update your NodeBB when we release it.

... which will be... soon:tm:

**Comment by julianlam** [comment]
On v1.x.x branch of NodeBB running latest composer version, and it's working fine here, actually...

**Comment by bdharrington7** [comment]
The errors I see are just the ones I posted.. Hmm I'm pretty sure I did this right,

* Git clone the repo into the nodebb/node_modules folder
* Switch to a particular version hash (using git bisect)
* Restart node bb

I even tried blowing away the node modules folder under the composer package and then `npm i` in that folder, the only thing I didn't try was npm i in the node bb root

**Comment by bdharrington7** [comment]
@julianlam what did you do to get it to work properly?

I changed the version pinned in the package.json to 4.0.1, even blowing away the whole node_modules folder and reinstalling. 

After doing that, the composer does come up, but the conditional buttons (like spoiler and upload) still don't show up. I'm running a separate route for the composer. Here are the error messages: (apologies for the minified versions, it doesn't seem to be un-minifying when running in dev and I didn't find an option to toggle)

**On Page reload:**
* *Uncaught TypeError: Cannot read property 'addButtonDispatch' of undefined:* at:
** `require(["composer/formatting"],function(a){a.addButtonDispatch("emoji-extended"`
* *Uncaught TypeError: Cannot read property 'addButton' of undefined* at:
** `require(['composer', 'composer/controls'], function(composer, controls) {
		composer.addButton('fa fa-eye-slash', function(textarea, selectionStart, selectionEnd)`

**On opening the composer:**
* *Uncaught TypeError: Cannot read property 'enhance' of undefined* at:
** `$(window).on('action:composer.enhance', function(ev, data) {
			require(['composer'], function(composer) {
				composer.enhance(data.container)`

**Comment by julianlam** [comment]
Ah, I only tested on the non static route config. I'll try again in a bit.

**Comment by bdharrington7** [comment]
It's really not working at all, I tried turning the static route off to see your fixes, but it's still crashing out.

**Comment by julianlam** [comment]
Yeah as mentioned earlier it's incompatible since it uses the new module bridging functionality in core, which is not in v1.x.x.

Is there anything stopping you from using the latest `master`?

**Comment by bdharrington7** [comment]
I'm just a little wary of using master, since things can be less stable, and there's not an easy way to revert (or rather, I haven't scripted out a clean, roll-backable upgrade path)

What version is community.nodebb on right now (nbb and composer)? I noticed that the composer is a lot more stable now on mobile!

**Comment by bdharrington7** [comment]
Closing as not going to be fixed
