### ISSUE TITLE
toolbar button color not defined

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/nodebb-plugin-composer-default#48]
This results in the toolbar buttons using the foreground color of the theme and the background color of the composer:

Screenshots from users:

Darkly:
![image](https://cloud.githubusercontent.com/assets/4257305/16327923/31608384-399a-11e6-9b63-3a534dc0d6f7.png)

Slate:
![image](https://cloud.githubusercontent.com/assets/4257305/16327927/3a46673e-399a-11e6-956b-10cffb4305cb.png)

**Comment by Tsaukpaetra** [comment]
Oh hey! There's my phone! :dancer:

**Comment by pichalite** [comment]
https://github.com/NodeBB/nodebb-plugin-composer-default/pull/47
