### ISSUE TITLE
Latest lines in composer are not clickable

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/nodebb-plugin-composer-default#6]
Critical UX problem.
Several latest lines in composer are not clickable.

**Comment by NicolasSiver** [comment]
It looks like because of this:

<img width="1417" alt="screen shot 2015-10-08 at 9 03 18 am" src="https://cloud.githubusercontent.com/assets/135263/10366977/b78c4a72-6d9b-11e5-8981-d1746f37e377.png">

**Comment by jacobbridges** [comment]
I've noticed this issue several times and it's very annoying. Was planning on diving into the source the weekend, hoping it will be a simple HTML change.

Anyone have an idea where to start? My first guess is the bug is located in persona.

**Comment by barisusakli** [comment]
Tits the transparent taskbar blocking the clicks its in persona

**Comment by robotanarchy** [comment]
Reproduced this in the latest Firefox (41.0.1) and Chromium (45.0.2454.101):
> When clicking the 'up'-arrow-icon, to make the textareas cover most of the screen, they work. But we usually need to have another post open while creating a new one.
> 
> Desktop resolution:
> 1366x768

@barisusakli thanks for pointing me to the duplicate, I didn't see this.

Maybe I'll dig into the source, too.

@jacobbridges start with the developer tools (F12), change the CSS there. Verify in the browser, that it works and then grep the source code for the css-class names and fix it there, too. Verify again, test at different resolutions etc. and then make a pull request.

**Comment by jacobbridges** [comment]
Thanks @robotanarchy. Sadly I cannot remove the entire div because then the red plus button for creating new topics at the bottom right corner of the screen disappears. I'll have to make the div smaller or something..

**Comment by robotanarchy** [comment]
Looks like it's fixed for me when setting left position from 0px to auto for that navigation bar:
```css
.navbar-fixed-bottom
{
    left: auto;
}
```
Can anyone confirm this?

**Comment by barisusakli** [comment]
It should probably be added on the .taskbar class. But yeah that fixes it since the taskbar doesn't span the entire window anymore.
