### ISSUE TITLE
Upload privileges don't work at all.

### ISSUE THREAD

**Issue by yariplus** [NodeBB/nodebb-plugin-composer-default#62]
The user can select a category they have privileges in, upload a file, then just change the dropdown to a category they don't have privileges in.

**Comment by yariplus** [comment]
Actually, they don't work at all. It's based entirely on a user-editable field.

https://github.com/NodeBB/nodebb-plugin-composer-default/blob/569f40cd9199de4c72d615b1dea69854653eed4d/static/lib/composer/uploads.js#L231-L232

**Comment by barisusakli** [comment]
Yeah the client side tells which cid the topic is being created in, since the user can change the category from the dropdown.

The problem is uploading and submitting the topic are two different steps so you can upload and change the category.

We either need to combine those two steps so uploading happens when you click submit, or find another way to prevent this.

The reason upload happens separately was so we could get the resulting url and insert it into the post body and render the preview.

**Comment by yariplus** [comment]
Okay.

As far as the category selector. I don't see a problem with just keeping the cid set at the category the composer is started in, forgoing the selector entirely. For situations where the category may be unknown, such as app.newTopic, there could be a modal with the category selector, which then launches the composer.

**Comment by yariplus** [comment]
Is the privilege meant to prevent the posting of an uploaded file, or to prevent the upload itself?

Since the poster could just upload to a different category, I'm guessing it's the posting of an uploaded file.

If that is the case, what if we leave it how it is now, but parse out links to uploaded files when the post is submitted.

**Comment by barisusakli** [comment]
I think we should change it so upload image/file are global privileges instead of per category.

**Comment by yariplus** [comment]
I tend to agree, but

I can think of several unmentionable forums where upload privileges per category make sense. Sure they could just upload to a different category, but not without violating forum rules.

**Comment by barisusakli** [comment]
We could somehow prevent them from posting if we save the cid in req.session when they upload, and when they change category and submit we can compare the cid to the one saved in req.session.

**Comment by pitaj** [comment]
Or we could save the files in category-specific directories

**Comment by yariplus** [comment]
I like the comparing the cid idea.

**Comment by julianlam** [comment]
Yes, the comparing of cids is actually quite novel, and I like it *especially* because if the cids don't match, we can even delete the picture from the server side (as it's essentially unused)

**Comment by pitaj** [comment]
But that would require parsing all images in posts, and would prevent an image from being used in posts from different categories.

**Comment by pitaj** [comment]
Maybe it would help if I could actually get my mind around a use case. Can you give an example of when upload permissions on a per-category basis would be useful, and explain why embed permissions wouldn't fulfill the same need?

**Comment by sorvani** [comment]
If you are making a new topic, the upload action when using the imgur plugin for pictures is really annoying because it does the complete upload and then fails after 100% when it tries to put in the URL.

Sticking to mentionable sites, I can see this in a game forum where people are allowed to reply but not post screenshots, etc. for spoiler reasons.

The imgur plugin is only an embed when done.

**Comment by sorvani** [comment]
Recent topic in the community on this upload issue.
https://community.nodebb.org/post/60493

**Comment by barisusakli** [comment]
@sorvani that seems like a separate issue, does it show a no privileges alert?

**Comment by sorvani** [comment]
The specifically linked post is not a separate issue. The thread was about the plugin in general. But the linked post is specifically about uploading an image before setting a category.

![0_1496074436795_upload-32554efb-740b-41e7-ace6-75639a9d3f17](https://i.imgur.com/k7hbwjU.png)

**Comment by barisusakli** [comment]
Oh yeah, if you don't select a category, then you get that error, since the cid is undefined. Changing the privilege to be a global privilege would fix that.

If we keep category level upload privileges we need to disable upload buttons until a category is selected.

**Comment by sorvani** [comment]
Disabling the upload button does not help if the user simply pastes into the editor, which is what I do all the time.

**Comment by barisusakli** [comment]
We can disable all the uploads client side until a category is selected.

**Comment by sorvani** [comment]
Then that is a great solution IMO. Topic creation is much less than topic replies.

**Comment by romeo-nxp** [comment]
How to change upload image/file to global privileges?

**Comment by abhinov2** [comment]
How and where to add more fa fa icons on the header of the composer.
From where $ is being added , due to which i was able to enter inline maths .

**Comment by julianlam** [comment]
Please direct unrelated discussion and questions to [our community support forum](//community.nodebb.org).
