### ISSUE TITLE
Separate route bug: icons wrapping block the submit / discard buttons

### ISSUE THREAD

**Issue by bdharrington7** [NodeBB/nodebb-plugin-composer-default#69]
Version: 4.1.7

If there are enough icons enabled in the composer, they block the discard / submit buttons: 
![image](https://cloud.githubusercontent.com/assets/4553795/18152518/427e771a-6fab-11e6-9ec6-84f8f9c2dcd8.png)

A refresh will ~~remove~~ hide the cloud upload (image upload?) icon (which shouldn't be there in the case of #68) as well as the disk drive (file upload) icon. Additionally, the spoilers icon (if you have that installed) will just disappear on a refresh

**Comment by julianlam** [comment]
Hm... is this the case for all options that are added via plugin? Bold, italics, are still there, though?

**Comment by bdharrington7** [comment]
It's the only one I'm aware of. Every button on the top row stays there, but they're the standard ones
