### ISSUE TITLE
iOS device image uploads same filename, causing "data loss"

### ISSUE THREAD

**Issue by anthony-njctl** [NodeBB/nodebb-plugin-composer-default#7]
iOS devices appear to upload everything as "image.jpeg" so if you upload more than one image within a single post prior to submitting the post, the earlier files get overwritten by the progress code.

uploadProgress: function(event, position, total, percent) { 
252 					for(var i=0; i < files.length; ++i) { 
253 						updateTextArea(files[i].name, 'uploading ' + percent + '%'); 
254 					} 
255 				}, 

I think that if the files array always contains unique file names, you can avoid this problem.  I manually tested it by uploading one image, renaming the tag to image0, then uploading another image.  the second image then uploads as "image.jpeg" and does not overwrite the previous

**Comment by anthony-njctl** [comment]
I tried to edit nodebb-plugin-composer-default/static/lib/composer/uploads.js and added a timestamp and array index to the filename but when I test it, I keep seeing image.jpeg used instead.  I'm not sure if I'm editing the wrong file, or if I'm just not reloading the module correctly

**Comment by barisusakli** [comment]
file name is used here too 
https://github.com/NodeBB/nodebb-plugin-composer-default/blob/master/static/lib/composer/uploads.js#L221

might need to loop true the files array and assign unique names to each before that loop

**Comment by anthony-njctl** [comment]
oh interesting.. I was trying to change the other places, because those are what pass in "params" to uploadContentFiles but I realize that I was trying to change the form data file names and not the actual files variable

**Comment by anthony-njctl** [comment]
I'm not sure why my changes don't seem to be taking.  I reload NodeBB after I make a change and nothing is being taken from node_modules/nodebb-plugin-composer-default/static/lib/composer/uploads.js

I even tried putting in some broken javascript which should make the upload fail but the upload keeps working.  I don't think my site is either recompiling the changes or something is getting cached

**Comment by barisusakli** [comment]
You have to restart after making js changes. Also disabled your cache.
