### ISSUE TITLE
composer.js not minified

### ISSUE THREAD

**Issue by phit** [NodeBB/nodebb-plugin-composer-default#70]
https://community.nodebb.org/topic/9453/performance-improvement/
made me look at google pagespeed for my site and I noticed composer.js is one of the two js files not being minified in a default nodebb installation
small enhancement, rather low priority but I figured might as well report it regardless

**Comment by barisusakli** [comment]
this should be fixed on latest, https://community.nodebb.org/assets/src/modules/composer.js
