### ISSUE TITLE
composer does not follow theme / skin settings

### ISSUE THREAD

**Issue by geransmith** [NodeBB/nodebb-plugin-composer-default#85]
When using the composer, Persona theme, and attempting to apply a skin, the composer keeps the white look. 

I am not sure if this is an issue with the composer, how with the theme not skinning the composer properly. Ultimately I'd like the look and feel to be consistent across the board. If a user has the Cyborg Bootswatch skin on, the composer should have the same dark theme to it.

**Comment by pitaj** [comment]
Unfortunately this is impossible while supporting user-selectable Bootswatch skins.

**Comment by tehspaceg** [comment]
Interesting! I guess we can close this then. Thanks for the quick reply.

**Comment by barisusakli** [comment]
This is doable, right now composer hardcodes the background to white and doesnt properly handle text colors, thats why it breaks on some skins. Should be fixable by using proper bs variables.

**Comment by barisusakli** [comment]
cyborg with hardcoded white bg
![image](https://user-images.githubusercontent.com/2583394/192099299-04147b2b-def7-4e66-b261-9af13e192c54.png)

cyborg after removing hardcoded white and using bs5 card-body class on the composer container and removing hardcoded color on formatting buttons.
![image](https://user-images.githubusercontent.com/2583394/192099460-2a8f813b-7f97-4c3d-ad4c-9606393bb8c5.png)

Just need to go through composer css and remove hardcoded bg/color values.

**Comment by pitaj** [comment]
Ah yeah because skins are compiled now.
