### ISSUE TITLE
Ability to disable tags on posts

### ISSUE THREAD

**Issue by PWesterdale** [NodeBB/nodebb-plugin-composer-default#87]
Before I wrote a PR I just wanted to check whether this would be likely to be accepted.
I have a large scale NodeBB forum and the tagging has got quite out of hand and I would like the ability to disable it.

**Comment by barisusakli** [comment]
Setting max and min tag count to 0 might already disable tagging give that a try.

**Comment by PWesterdale** [comment]
Hey, I already tried that - Was my initial thought as to adding logic to hide the tag area in the template.

**Comment by barisusakli** [comment]
Setting max and min tag count to 0 might already disable tagging give that a try.

**Comment by PWesterdale** [comment]
I have tried this - it just allows me to enter text and then when I press enter no tag is created.
