### ISSUE TITLE
Unable to retemplate composer through themes?

### ISSUE THREAD

**Issue by zombachu** [NodeBB/nodebb-plugin-composer-default#94]
I've tried creating a `composer.tpl` file in my theme's `templates` folder, but the default composer continues to be used. I've verified that my custom `composer.tpl` is being overriden entirely through the following code not returning my own template:

``` javascript
ajaxify.loadTemplate('composer', function(composer) {
    var composerEl = templates.parse(composer);
    console.log(composerEl);
});
```

Am I doing something wrong or is the composer not meant to be themed in the first place?

**Comment by julianlam** [comment]
It can be overridden... Check out the plugin order? Move the theme after the composer maybe.

**Comment by zombachu** [comment]
@julianlam Oh thanks, that worked. I completely forgot that was an option. Sorry for bothering you!
