### ISSUE TITLE
Tags do not appear if "Use a seperate route for the composer" is enabled

### ISSUE THREAD

**Issue by jimmykane** [NodeBB/nodebb-plugin-composer-default#98]
Tags do not appear if "Use a separate route for the composer" is enabled

Theme levander. 
Composer as the first plugin to load. What am I missing here?

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-composer-default/commit/8caa39ab5dcd8d0bcc73c5133c8b5013f139bd6a
